server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/smart_campus_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:change-this-secret-before-production-deployment-123456789}
  expiration: ${JWT_EXPIRATION:3600000}
