import { useEffect, useState } from "react";
import api from "../api/axios";
import "./RolePortal.css";

const Card = ({ label, value, note }) => <div className="rp-card"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>;
const Header = ({ title, text }) => <div className="rp-head"><div><p>SMART CAMPUS</p><h1>{title}</h1><span>{text}</span></div><div className="rp-badge">Live Portal</div></div>;

export function TeacherDashboard() {
  const [profile,setProfile]=useState(null), [students,setStudents]=useState([]);
  useEffect(()=>{Promise.all([api.get("/teachers/me"),api.get("/students")]).then(([p,s])=>{setProfile(p.data);setStudents(s.data||[])}).catch(()=>{});},[]);
  return <><Header title={`Welcome${profile?.name ? `, ${profile.name}` : ""}`} text="Manage your classes and student activity from one place."/><div className="rp-grid"><Card label="Students" value={students.length} note="Available student records"/><Card label="Role" value="Teacher" note="Authorized faculty access"/><Card label="Status" value="Active" note="Account is ready"/></div><section className="rp-panel"><h2>Quick overview</h2><p>Use the navigation to review students, record attendance and manage your faculty profile.</p></section></>;
}

export function TeacherStudents(){const [data,setData]=useState([]);useEffect(()=>{api.get("/students").then(r=>setData(r.data||[])).catch(()=>{})},[]);return <><Header title="Students" text="Students available to your faculty account."/><div className="rp-table"><table><thead><tr><th>ID</th><th>Name</th><th>Email</th></tr></thead><tbody>{data.map(s=><tr key={s.id}><td>#{s.id}</td><td>{s.name||"Student"}</td><td>{s.email||"—"}</td></tr>)}</tbody></table></div></>}

export function TeacherAttendance(){const [studentId,setStudentId]=useState(""),[courseId,setCourseId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[present,setPresent]=useState(true),[msg,setMsg]=useState("");const submit=async e=>{e.preventDefault();setMsg("");try{await api.post(`/attendance?studentId=${studentId}&courseId=${courseId}&date=${date}&present=${present}`);setMsg("Attendance saved successfully.")}catch(err){setMsg(err.response?.data?.message||"Could not save attendance.")}};return <><Header title="Mark Attendance" text="Record student attendance securely."/><form className="rp-form" onSubmit={submit}><label>Student ID<input value={studentId} onChange={e=>setStudentId(e.target.value)} required/></label><label>Course ID<input value={courseId} onChange={e=>setCourseId(e.target.value)} required/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Status<select value={String(present)} onChange={e=>setPresent(e.target.value==="true")}><option value="true">Present</option><option value="false">Absent</option></select></label><button>Save Attendance</button>{msg&&<p className="rp-message">{msg}</p>}</form></>}

function Profile({type}){const [p,setP]=useState(null);useEffect(()=>{api.get(type==="teacher"?"/teachers/me":"/students/me").then(r=>setP(r.data)).catch(()=>{})},[type]);return <><Header title="My Profile" text="Your Smart Campus account information."/><section className="rp-profile"><div className="rp-avatar">{(p?.name||type)[0].toUpperCase()}</div><div><h2>{p?.name||`${type[0].toUpperCase()+type.slice(1)} Account`}</h2><p>{p?.email||"Profile email"}</p><span>{type.toUpperCase()}</span></div></section></>}
export const TeacherProfile=()=> <Profile type="teacher"/>;

export function StudentDashboard(){const [p,setP]=useState(null),[a,setA]=useState([]);useEffect(()=>{Promise.all([api.get("/students/me"),api.get("/attendance/me")]).then(([x,y])=>{setP(x.data);setA(y.data||[])}).catch(()=>{})},[]);const present=a.filter(x=>x.present).length;return <><Header title={`Welcome${p?.name?`, ${p.name}`:""}`} text="Track your academic profile and attendance."/><div className="rp-grid"><Card label="Attendance Records" value={a.length} note="Total recorded classes"/><Card label="Present" value={present} note="Classes attended"/><Card label="Status" value="Active" note="Student account"/></div><section className="rp-panel"><h2>Student workspace</h2><p>Your profile and attendance records are available from the navigation menu.</p></section></>}
export function StudentAttendance(){const [data,setData]=useState([]);useEffect(()=>{api.get("/attendance/me").then(r=>setData(r.data||[])).catch(()=>{})},[]);return <><Header title="My Attendance" text="Your latest attendance records."/><div className="rp-table"><table><thead><tr><th>Date</th><th>Course</th><th>Status</th></tr></thead><tbody>{data.map((a,i)=><tr key={a.id||i}><td>{a.date||"—"}</td><td>{a.course?.name||a.course?.courseName||`Course ${a.course?.id||""}`}</td><td><span className={a.present?"rp-present":"rp-absent"}>{a.present?"Present":"Absent"}</span></td></tr>)}</tbody></table></div></>}
export const StudentProfile=()=> <Profile type="student"/>;